services:
  db:
    image: postgres:17
    container_name: allsad_db
    env_file:
      - .env-none-dev
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  allsad:
    image: allsad_app
    build:
      context: .
    container_name: allsad_app
    env_file:
      - .env-none-dev
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    command: ["/entrypoint.sh"]

