"""Add Size

Revision ID: 670b3484d516
Revises: 1d6590fb7cba
Create Date: 2024-12-05 18:28:47.393111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670b3484d516'
down_revision: Union[str, None] = '1d6590fb7cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('size', sa.String(), nullable=False))
    op.alter_column('card', 'image',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(),
                    nullable=False)
    op.alter_column('category', 'image',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'image',
                    existing_type=sa.String(),
                    type_=sa.INTEGER(),
                    nullable=True)
    op.alter_column('card', 'image',
                    existing_type=sa.String(),
                    type_=sa.INTEGER(),
                    nullable=True)
    op.drop_column('card', 'size')
    # ### end Alembic commands ###
