"""Add vkid in user

Revision ID: 91aa904e9af3
Revises: 40a8365890fd
Create Date: 2024-12-11 02:20:48.123024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91aa904e9af3'
down_revision: Union[str, None] = '40a8365890fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('vk_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['vk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'vk_id')
    # ### end Alembic commands ###
